Repository cloudposse/github-action-docker-build-push, pull requests merged in 2022-09, with the labels that each got.

#10 Bug Fix: Create `docker context` before running `buildx`
  action.yml
Labels: bugfix

#11 Added `file` parameter as `Dockerfile`
  action.yml
Labels: major

#13 Added test for non default Dockerfile
  .github/workflows/test-docker-build-complex.yml
  README.md
  action.yml
  docs/github-action.md
  test/custom/Dockerfile_complex
Labels: minor

#15 Fix docker create context
  action.yml
Labels: minor

#16 Add build args
  .github/workflows/test-docker-build-complex.yml
  README.md
  action.yml
  docs/github-action.md
  test/custom/Dockerfile_complex
Labels: minor
